INSERT INTO libros (nombre, autor, editorial, disponible, cantidad, ano, sinopsis) VALUES ('Carrie', 'Stephen King', 'Pomaire','si', 7, '1974', 'Carrie, una joven de apariencia insignificante, acosada por sus compañeras de instituto, vive con su madre, una fanática religiosa.');
INSERT INTO libros (nombre, autor, editorial, disponible, cantidad, ano, sinopsis) VALUES ('El Resplandor', 'Stephen King', 'Pomaire', 'si', 3, '1977', 'Jack Torrance acepta una oferta de trabajo en un hotel de montaña que se encuentra a 65 kilómetros del pueblo más cercano.');
INSERT INTO libros (nombre, autor, editorial, disponible, cantidad, ano, sinopsis) VALUES ('EL Cazador De Sueños', 'Stephen King', 'Pomaire', 'si', 1, '2001', 'Situada en la ciudad ficticia de Derry, Maine, El cazador de sueños es la historia de cuatro amigos cuyas vidas son alteradas al salvar a Douglas Duddits Cavell.');
INSERT INTO libros (nombre, autor, editorial, disponible, cantidad, ano, sinopsis) VALUES ('Rebelion en la Granja', 'George Orwell', 'Pomaire', 'si', 1, '1945', 'Los animales de la granja de los Jones se sublevan contra sus dueños humanos y los vencen. ');
INSERT INTO libros (nombre, autor, editorial, disponible, cantidad, ano, sinopsis) VALUES ('The Last Time I Lied', 'Riley Sager Nikolaus', 'O’Reilly and Lehner', 'no', 0, '2018', 'La trama trata de la reapertura de un campamento de verano del que desaparecieron tres niñas 15 años antes.');
INSERT INTO libros (nombre, autor, editorial, disponible, cantidad, ano, sinopsis) VALUES ('La chica del tren', 'Paula Hawkins', 'Ediciones B', 'si', 1, '2016', 'La protagonista Rachel se ha sumido en el alcoholismo por una serie de desgracias.');
INSERT INTO libros (nombre, autor, editorial, disponible, cantidad, ano, sinopsis) VALUES ('La chica que dejaste atrás', 'Jojo Moyes', 'Ediciones Salamandra', 'no', 0, '2017','Dos mujeres separadas por un siglo pero unidas por su determinación a luchar por lo que más aman.');
INSERT INTO libros (nombre, autor, editorial, disponible, cantidad, ano, sinopsis) VALUES ('El jardín de las mariposas', 'Dot Hutchison', 'Ediciones B', 'no', 0, '2016', 'Cerca de una aislada mansión existe un jardín donde se cultivan delicadas flores y en él, habita una exquisita y peculiar colección de mariposas que es resguardada por el Jardinero, un hombre que desconoce los límites de su obsesión por preservar la belleza.');
INSERT INTO usuarios (nombre, email, telefono) VALUES ('Pepe', 'pepe@gmail.com', '1233123');
INSERT INTO usuarios (nombre, email, telefono) VALUES ('Pepe', 'pepe@gmail.com', '12123');
INSERT INTO usuarios (nombre, email, telefono) VALUES ('Pepe', 'pepe@gmail.com', '123123');
INSERT INTO usuarios (nombre, email, telefono) VALUES ('Pepe', 'pepe@gmail.com', '3123123');
INSERT INTO usuarios (nombre, email, telefono) VALUES ('Pepe', 'pepe@gmail.com', '123123');
INSERT INTO usuarios (nombre, email, telefono) VALUES ('Pepe', 'pepe@gmail.com', '12323');
INSERT INTO usuarios (nombre, email, telefono) VALUES ('Pepe', 'pepe@gmail.com', '12323123');
INSERT INTO usuarios (nombre, email, telefono) VALUES ('Pepe', 'pepe@gmail.com', '1123123');
INSERT INTO usuarios (nombre, email, telefono) VALUES ('Pepe', 'pepe@gmail.com', '3123123');
INSERT INTO usuarios (nombre, email, telefono) VALUES ('Pepe', 'pepe@gmail.com', '23123');
INSERT INTO usuarios (nombre, email, telefono) VALUES ('Pepe', 'pepe@gmail.com', '123');
INSERT INTO usuarios (nombre, email, telefono) VALUES ('Pepe', 'pepe@gmail.com', '1223');
INSERT INTO usuarios (nombre, email, telefono) VALUES ('Pepe', 'pepe@gmail.com', '12');
INSERT INTO usuarios (nombre, email, telefono) VALUES ('Pepe', 'pepe@gmail.com', '123123');
